# Generated by Django 4.2.13 on 2024-05-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daynumber', models.IntegerField()),
                ('surveyid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='currentDay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.courseday'),
        ),
    ]
