# Generated by Django 4.2.13 on 2024-05-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_survey_alter_user_currentday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseday',
            name='surveyid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.survey'),
        ),
    ]
